services:
  db:
    image: postgres:15
    container_name: bankapi_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankapi_app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "/wait-for db:5432 -t 60 -- echo 'Banco disponível!' && npx sequelize-cli db:migrate && npm run dev"

volumes:
  pgdata:
